### ISSUE TITLE
UNIQUE constraint failed

### ISSUE THREAD

**Issue by vporton** [arcamens/django-debits#10]
```
Internal Server Error: /paypal/ipn
Traceback (most recent call last):
  File "/home/debits/.virtualenvs/debits/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/debits/.virtualenvs/debits/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: debits_base_subscription.transaction_id
```
(apparently when clicking "Switch" button).

**Comment by vporton** [comment]
The error is in `create_active_subscription()` in `debits_base.models`.

**Comment by vporton** [comment]
cannot reprise the bug, closing
